/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lifeunderwaterapp;

import javax.swing.JFrame;

/**
 *
 * @author CamaraAdmin
 */
public class WildlifeGUI extends javax.swing.JFrame {

    /**
     * Creates new form WildlifeGUI
     */
    public WildlifeGUI() {
        initComponents();
        setTitle("Wildelife GUI");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        /*the textfeilds will be hidden on open with the use of the below code*/
        sharktxt.setVisible(false);
        fishtxt.setVisible(false);
        shellfishtxt.setVisible(false);
        formPanel.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        gamebtn = new javax.swing.JButton();
        HomeBtn = new javax.swing.JButton();
        sharkbtn = new javax.swing.JRadioButton();
        fishbtn = new javax.swing.JRadioButton();
        shellfishbtn = new javax.swing.JRadioButton();
        quizbtn = new javax.swing.JButton();
        sharklbl = new javax.swing.JLabel();
        fishlbl = new javax.swing.JLabel();
        shellfishlbl = new javax.swing.JLabel();
        sharktxt = new javax.swing.JTextField();
        fishtxt = new javax.swing.JTextField();
        shellfishtxt = new javax.swing.JTextField();
        formbtn = new javax.swing.JButton();
        formPanel = new javax.swing.JPanel();
        namelbl = new javax.swing.JLabel();
        emaillbl = new javax.swing.JLabel();
        emailtxt = new javax.swing.JTextField();
        questionlbl = new javax.swing.JLabel();
        questiontxt = new javax.swing.JTextField();
        nametxt = new javax.swing.JTextField();
        addbtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        savebtn = new javax.swing.JButton();
        displaybtn = new javax.swing.JButton();
        submitbtn = new javax.swing.JButton();
        submitlbl = new javax.swing.JLabel();
        homebtn = new javax.swing.JButton();
        sharkgamebtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 153, 255));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gamebtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        gamebtn.setText("Tic Tac Shark Game.");
        gamebtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        gamebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        gamebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gamebtnActionPerformed(evt);
            }
        });
        jPanel1.add(gamebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 150, 30));

        HomeBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        HomeBtn.setText("Home");
        HomeBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        HomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBtnActionPerformed(evt);
            }
        });
        jPanel1.add(HomeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 30));

        sharkbtn.setText("Sharks");
        sharkbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sharkbtnActionPerformed(evt);
            }
        });
        jPanel1.add(sharkbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        fishbtn.setText("Fish");
        fishbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fishbtnActionPerformed(evt);
            }
        });
        jPanel1.add(fishbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, -1, -1));

        shellfishbtn.setText("Shellfish");
        shellfishbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shellfishbtnActionPerformed(evt);
            }
        });
        jPanel1.add(shellfishbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, -1, -1));

        quizbtn.setText("Click to test your metal.");
        quizbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(quizbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 486, 139, 38));

        sharklbl.setMaximumSize(new java.awt.Dimension(259, 220));
        sharklbl.setMinimumSize(new java.awt.Dimension(259, 220));
        jPanel1.add(sharklbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 250, 180));
        jPanel1.add(fishlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 220, 180));
        jPanel1.add(shellfishlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, 240, 180));

        sharktxt.setBackground(new java.awt.Color(0, 153, 153));
        sharktxt.setText("bullet points about sharks underwater");
        jPanel1.add(sharktxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 250, 190));

        fishtxt.setBackground(new java.awt.Color(0, 155, 155));
        fishtxt.setText("jTextField2");
        jPanel1.add(fishtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 220, 190));

        shellfishtxt.setBackground(new java.awt.Color(0, 155, 155));
        shellfishtxt.setText("jTextField3");
        shellfishtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shellfishtxtActionPerformed(evt);
            }
        });
        jPanel1.add(shellfishtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, 240, 190));

        formbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        formbtn.setText("Form Page");
        formbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        formbtn.setMaximumSize(new java.awt.Dimension(109, 20));
        formbtn.setMinimumSize(new java.awt.Dimension(109, 20));
        formbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formbtnActionPerformed(evt);
            }
        });
        jPanel1.add(formbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 100, 30));

        formPanel.setBackground(new java.awt.Color(0, 155, 155));
        formPanel.setLayout(null);

        namelbl.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        namelbl.setText("Name:");
        formPanel.add(namelbl);
        namelbl.setBounds(20, 20, 60, 19);

        emaillbl.setText("E-mail:");
        formPanel.add(emaillbl);
        emaillbl.setBounds(20, 80, 60, 20);
        formPanel.add(emailtxt);
        emailtxt.setBounds(20, 110, 220, 22);

        questionlbl.setText("Question:");
        formPanel.add(questionlbl);
        questionlbl.setBounds(20, 146, 100, 20);

        questiontxt.setText("jTextField4");
        formPanel.add(questiontxt);
        questiontxt.setBounds(20, 180, 220, 100);
        formPanel.add(nametxt);
        nametxt.setBounds(20, 40, 210, 22);

        addbtn.setText("Add");
        formPanel.add(addbtn);
        addbtn.setBounds(20, 300, 72, 23);

        deletebtn.setText("Delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });
        formPanel.add(deletebtn);
        deletebtn.setBounds(120, 300, 72, 23);

        savebtn.setText("Save");
        formPanel.add(savebtn);
        savebtn.setBounds(20, 340, 72, 23);

        displaybtn.setText("Display");
        formPanel.add(displaybtn);
        displaybtn.setBounds(120, 340, 72, 23);

        submitbtn.setText("Submit your question! :)");
        formPanel.add(submitbtn);
        submitbtn.setBounds(20, 390, 180, 23);

        submitlbl.setText("jLabel2");
        formPanel.add(submitlbl);
        submitlbl.setBounds(310, 20, 300, 410);

        homebtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        homebtn.setText("Home");
        homebtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebtnActionPerformed(evt);
            }
        });
        formPanel.add(homebtn);
        homebtn.setBounds(620, 30, 90, 24);

        sharkgamebtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sharkgamebtn.setText("Shark Tac Toe");
        sharkgamebtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sharkgamebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sharkgamebtnActionPerformed(evt);
            }
        });
        formPanel.add(sharkgamebtn);
        sharkgamebtn.setBounds(740, 30, 120, 24);

        jPanel1.add(formPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 450));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 0, 870, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void HomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBtnActionPerformed
        // TODO add your handling code here:
        LifeUnderWaterGUI lifeUnderWaterGUI = new LifeUnderWaterGUI();
        lifeUnderWaterGUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_HomeBtnActionPerformed

    private void gamebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gamebtnActionPerformed
        // TODO add your handling code here:
        WildlifeGame wildLifeGame = new WildlifeGame();
        wildLifeGame.setVisible(true);
        dispose();
    }//GEN-LAST:event_gamebtnActionPerformed

    private void shellfishtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shellfishtxtActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_shellfishtxtActionPerformed

    private void sharkbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sharkbtnActionPerformed
        // TODO add your handling code here:
        if(sharkbtn.isSelected()){
            sharktxt.setVisible(true);
        }
        else{
            sharktxt.setVisible(false);
        }
    }//GEN-LAST:event_sharkbtnActionPerformed

    private void fishbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fishbtnActionPerformed
        // TODO add your handling code here:
        if(fishbtn.isSelected()){
            fishtxt.setVisible(true);
        }
        else{
            fishtxt.setVisible(false);
        }
    }//GEN-LAST:event_fishbtnActionPerformed

    private void shellfishbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shellfishbtnActionPerformed
        // TODO add your handling code here:
          if(shellfishbtn.isSelected()){
            shellfishtxt.setVisible(true);
        }
        else{
            shellfishtxt.setVisible(false);
        }
        
    }//GEN-LAST:event_shellfishbtnActionPerformed

    private void formbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formbtnActionPerformed
        // TODO add your handling code here:
             // Set the content pane to be the form panel
    setContentPane(formPanel);
    formPanel.setVisible(true);

    // Repaint the frame to reflect the changes
    revalidate();
    repaint();
    }//GEN-LAST:event_formbtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deletebtnActionPerformed

    private void homebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebtnActionPerformed
        // TODO add your handling code here:
        //formpage home btn;
          LifeUnderWaterGUI lifeUnderWaterGUI = new LifeUnderWaterGUI();
        lifeUnderWaterGUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_homebtnActionPerformed

    private void sharkgamebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sharkgamebtnActionPerformed
        // TODO add your handling code here:
           WildlifeGame wildLifeGame = new WildlifeGame();
        wildLifeGame.setVisible(true);
        dispose();
    }//GEN-LAST:event_sharkgamebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WildlifeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WildlifeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WildlifeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WildlifeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WildlifeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HomeBtn;
    private javax.swing.JButton addbtn;
    private javax.swing.JButton deletebtn;
    private javax.swing.JButton displaybtn;
    private javax.swing.JLabel emaillbl;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JRadioButton fishbtn;
    private javax.swing.JLabel fishlbl;
    private javax.swing.JTextField fishtxt;
    private javax.swing.JPanel formPanel;
    private javax.swing.JButton formbtn;
    private javax.swing.JButton gamebtn;
    private javax.swing.JButton homebtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel namelbl;
    private javax.swing.JTextField nametxt;
    private javax.swing.JLabel questionlbl;
    private javax.swing.JTextField questiontxt;
    private javax.swing.JButton quizbtn;
    private javax.swing.JButton savebtn;
    private javax.swing.JRadioButton sharkbtn;
    private javax.swing.JButton sharkgamebtn;
    private javax.swing.JLabel sharklbl;
    private javax.swing.JTextField sharktxt;
    private javax.swing.JRadioButton shellfishbtn;
    private javax.swing.JLabel shellfishlbl;
    private javax.swing.JTextField shellfishtxt;
    private javax.swing.JButton submitbtn;
    private javax.swing.JLabel submitlbl;
    // End of variables declaration//GEN-END:variables
}
